<html>
<head>
<title>Untitled Document</title>
<meta http-equiv="Content-Type" content="text/html; charset=euc-kr">
<style type="text/css">
<!--
td {  font-size: 9pt}
-->
</style>
</head>

<body bgcolor="#FFFFFF">
<table width="250" border="3" cellspacing="0" cellpadding="0" bordercolor="#999999" bgcolor="#EBEBEB">
  
  <form  name="login" Method="Post" Action="cookie_update.asp">  
  <tr>
    <td>
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr> 
          <td width="29%" align="center">&nbsp;</td>
          <td width="71%">&nbsp; </td>
        </tr>
        <tr> 
          <td width="29%" height="20" align="center">아이디 :</td>
          <td width="71%" height="20"> 
            <input type="text" name="ID">
          </td>
        </tr>
        <tr> 
          <td width="29%" height="20" align="center">이&nbsp;&nbsp;&nbsp;름 :</td>
          <td width="71%" height="20"> 
            <input type="text" name="NAME">
          </td>
        </tr>
        <tr> 
          <td width="29%" height="20" align="center">나&nbsp;&nbsp;&nbsp;이 :</td>
          <td width="71%" height="20"> 
            <input type="text" name="AGE">
          </td>
        </tr>
        <tr> 
          <td width="29%" height="20" align="center">성&nbsp;&nbsp;&nbsp;별 :</td>
          <td width="71%" height="20"> 남 
            <input type="radio" name="SEX" value="1">
            여 
            <input type="radio" name="SEX" value="2">
          </td>
        </tr>
        <tr> 
          <td colspan="2" height="50" align="center"> 
            <input type="submit"  value="완    료">
            <input type="reset"  value="취    소">
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
</body>
</html>
